"""
Django settings for entom_site project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


def get_env(name, default=None, required=False):
    value = os.environ.get(name, default)
    if required and (value is None or str(value).strip() == ""):
        raise ImproperlyConfigured(f"Falta la variable de entorno requerida: {name}")
    return value

# En producción: DEBUG=False. Render pone la variable DEBUG=False en el entorno.
DEBUG = get_env("DEBUG", "True") == "True"

# SECRET_KEY solo puede usar fallback en desarrollo local.
SECRET_KEY = get_env("SECRET_KEY", required=not DEBUG)
if not SECRET_KEY:
    SECRET_KEY = "dev-only-insecure-secret-key"

# Hosts permitidos: en Render agrega tu dominio .onrender.com y el dominio final.
ALLOWED_HOSTS = [host.strip() for host in get_env("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if host.strip()]

# Dominio de producción siempre permitido (se añade vía variable de entorno en Render)
# ALLOWED_HOSTS en Render debe contener:
# fumigacionesentom.com,www.fumigacionesentom.com,fumigaciones-entom-web.onrender.com


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cloudinary_storage",
    "cloudinary",
    "products",
    "services",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise debe ir inmediatamente después de SecurityMiddleware
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "entom_site.urls"



TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "entom_site" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.template.context_processors.static",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]



WSGI_APPLICATION = "entom_site.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# - Local: usa SQLite (sin variable DATABASE_URL en el entorno)
# - Render: usa PostgreSQL (Render inyecta DATABASE_URL automáticamente)
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "es-mx"

TIME_ZONE = "America/Mexico_City"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

# Configuración para archivos multimedia (fotos de productos)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Directorios de archivos estáticos en desarrollo (dentro del repositorio)
# Aquí vive tu entom_site/static/ con css/site.css, js/site.js, etc.
STATICFILES_DIRS = [
    BASE_DIR / "entom_site" / "static",
]

# Carpeta donde 'collectstatic' colocará todos los estáticos para producción
# (normalmente fuera del repositorio o en una ruta servida por Nginx/Apache)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Django 6 usa STORAGES en lugar de DEFAULT_FILE_STORAGE / STATICFILES_STORAGE.
# Media va a Cloudinary en producción. Si las credenciales no existen y DEBUG=True,
# Django usa almacenamiento local para no exponer secretos en el repositorio.
cloud_name = get_env("CLOUDINARY_CLOUD_NAME")
cloud_api_key = get_env("CLOUDINARY_API_KEY")
cloud_api_secret = get_env("CLOUDINARY_API_SECRET")

has_cloudinary_credentials = all([cloud_name, cloud_api_key, cloud_api_secret])

if not DEBUG and not has_cloudinary_credentials:
    raise ImproperlyConfigured(
        "Cloudinary requiere CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY y CLOUDINARY_API_SECRET en producción."
    )

STORAGES = {
    "default": {
        "BACKEND": (
            "cloudinary_storage.storage.MediaCloudinaryStorage"
            if has_cloudinary_credentials
            else "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

if has_cloudinary_credentials:
    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": cloud_name,
        "API_KEY": cloud_api_key,
        "API_SECRET": cloud_api_secret,
    }


