# Generated by Django 6.0.2 on 2026-03-19 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un servicio con ese nombre.'}, max_length=200, unique=True, verbose_name='Nombre del servicio')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Imagen del servicio')),
                ('service_type', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], max_length=20, verbose_name='Tipo de servicio')),
                ('method', models.CharField(choices=[('AM', 'Asperción manual'), ('AMO', 'Asperción motorizada'), ('INYECCION', 'Inyección'), ('NEBULIZACION', 'Nebulización'), ('TERMO', 'Termonebulización'), ('APLMAN', 'Aplicación manual'), ('ESPUMA', 'Espuma'), ('ESPOLVO', 'Espolvoreo')], max_length=20, verbose_name='Método aplicado')),
                ('estimated_time', models.CharField(blank=True, max_length=100, verbose_name='Tiempo estimado')),
                ('materials_description', models.TextField(blank=True, verbose_name='Materiales utilizados')),
                ('benefits', models.TextField(blank=True, verbose_name='Beneficios')),
                ('recommended_for', models.TextField(blank=True, verbose_name='Recomendado para')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-created_at'],
            },
        ),
    ]
