# Generated by Django 6.0.2 on 2026-03-11 08:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe una categoría con ese nombre.'}, max_length=50, unique=True, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un producto con ese nombre.'}, max_length=100, unique=True, verbose_name='Nombre del producto')),
                ('description', models.TextField(max_length=300, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Inventario')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Peso (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='título')),
                ('alt_text', models.CharField(blank=True, max_length=120, verbose_name='texto alternativo')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Orden en carrusel (0, 1, 2)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'sort_order'), name='unique_sort_per_product')],
            },
        ),
    ]
