# Generated by Django 6.0.2 on 2026-03-12 18:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('L', 'L'), ('mL', 'mL')], default='kg', help_text='Selecciona la unidad de la presentación (kg, g, L, mL).', max_length=3, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Número de la presentación. Ej.: 1.200 (kg), 500.000 (mL), 0.750 (L).', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Cantidad'),
        ),
    ]
